#!/bin/bash

CMD=$( basename $0 )
VERSION="0.1"
USAGE="Usage: $CMD [-h] [-m mode] [-a bitrate | -v quality ] inputfiles ..."

# ---------------------------------------------------------
function printusage () {
  test "$1" && echo -e >&2 "$CMD: $1"
  echo >&2 "$USAGE"
  exit 2
}
# ---------------------------------------------------------
function printhelp () {
  cat << EOF
ogg2mp3 version $VERSION 

Bulk transcoding of OGG Vorbis to MP3. 

$USAGE

Options:
  -h, --help            Print help
  -q, --quiet           Do not print verbose messages.
  -m, --mode=MODE       Define stereo mode where MODE may be (j)oint,
                        (s)imple, (f)orce, (d)dual-mono, (m)ono
  -a, --abr=BITRATE     Use ABR encoding method with specified average
                        bit rate. See LAME man page for details.
  -v, --vbr=QUALITY     Use VBR encoding method with specified quality
                        setting. See LAME man page for details.
EOF
  exit 0
}
# ---------------------------------------------------------
function print () {
   C=$1
   shift
   for MSG in "$@"; do
      echo >&$C "$MSG"
   done
}
# ---------------------------------------------------------
function verbose () {
  [ "$QUIET" ] || print 1 "$@"
}
# ---------------------------------------------------------
function warn () {
  print 2 "$@"
}
# ---------------------------------------------------------
function fail () {
  print 2 "$@"
  exit 1
}

# ---------------------------------------------------------
# parse command line options
# ---------------------------------------------------------

OPTS=$( getopt -n $CMD -o h?qm:a:v: --long help,mode:,abr:,vbr: -- "$@" )
eval set -- $OPTS

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|-\?|--help)  printhelp;;
    -q|--quiet)     QUIET="TRUE";;
    -m|--mode)      MODE="$2"; shift;;
    -a|--abr)       ABR="$2"; shift;;
    -v|--vbr)       VBR="$2"; shift;;
    --)             shift; break;; # $@ is used below
    *)              printusage "Invalid option '$1'!";;
  esac
  shift
done

[[ "$ABR" && "$VBR" ]] && printusage "Only either ABR or VBR is allowed!"
[[ "$1" ]] || printusage "No input files defined!"
[[ "$ABR" || "$VBR" ]] || AUTOABR="TRUE"

# set encoding method
test "$MODE" && MODE="-m ${MODE:0:1}"
test "$ABR" && METHOD="--abr $ABR"
test "$VBR" && METHOD="--vbr-new -V $VBR"

verbose "mode option:    $MODE"
verbose "method option:  $METHOD"

# ---------------------------------------------------------
# transcode 
# ---------------------------------------------------------

function transcode () {

   function parsetag () {
     echo "$1" | grep "$2=" | cut -d= -f2
   }

   # read ogginfo output
   OGGINFO=$( ogginfo "$1" )
   test "$?" != "0" && fail "ogginfo failed!" "$OGGINFO"
 
   # parse nominal bitrate
   if [ "$AUTOABR" ]; then
      BITRATE=$( echo "$OGGINFO" | grep "Nominal bitrate:" | cut -d' ' -f3 )
      test "$BITRATE" || fail "Unable to parse bitrate!"
      verbose "Bitrate: $BITRATE"
      METHOD=--abr $BITRATE
   fi

   # parse tags
   ARTIST=$( parsetag "$OGGINFO" "artist" )
   ALBUM=$( parsetag "$OGGINFO" "album" )
   TITLE=$( parsetag "$OGGINFO" "title" )
   TRACKNUMBER=$( parsetag "$OGGINFO" "tracknumber" )
   YEAR=$( parsetag "$OGGINFO" "date" )
   GENRE=$( parsetag "$OGGINFO" "genre" )
   COMMENT=$( parsetag "$OGGINFO" "comment" )
   
   # decode | encode
   oggdec -Q -o- "$1" | lame -S $MODE $METHOD -q7 \
      --ta "$ARTIST" --tt "$TITLE" --ta "$ALBUM" --ty "$YEAR" --tn "$TRACKNUMBER" --tg "$GENRE" -tc "$COMMENT" \
	  - "${1/.ogg/.mp3}"
}

# ---------------------------------------------------------
#  process recursion
# ---------------------------------------------------------

function isogg () {
   # grep will have an error exit status if nothing was matched
   file "$1" | grep "Ogg data" | grep "Vorbis audio" > /dev/null
}

function processfile () {
   FILE="$@"
   
   # fail if invalid file
   test -r "$FILE" || fail "Unable to read file '$FILE'!"
   
   # if directory, process content
   if [ -d "$FILE" ]; then
      verbose "Processing directory '$FILE' ..."
      for SUBFILE in "$FILE"/*; do
      
         processfile "$SUBFILE"
      done

   # else: transcode file if ogg
   else
      verbose "Processing file '$FILE' ..."
      if isogg "$FILE"; then 
         transcode "$FILE"
      else
         warn "Not an Ogg Vorbis file: '$FILE'"
      fi
   fi
}

# ---------------------------------------------------------
#  main (recursion start)
# ---------------------------------------------------------

for FILE in "$@"; do
   processfile "$FILE"
done


